force-app/main/default/objects/ordens_de_venda__c/ordens_de_venda__c.object-meta.xml
<CustomObject>
    <description>Local onde serão registrados todos os pedidos de venda</description>
    <label>Ordem de venda</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>ID do pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens de venda</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ordens_de_venda__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Pendente</fullName>
                <default>true</default>
                <label>Em andamento</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeleteRecordsByStatus.cls
public with sharing class DeleteRecordsByStatus{

    /*public Static PageReference redirectToHome() {
        PageReference pgRef = new pageReference('/lightning/o/ordens_de_venda__c/list?filterName=Recent');
        pgRef.setRedirect(true);
        return pgRef;
       
    } 
    */
    


     public Static void deleteRecordsByStatus(List<Ordens_de_venda__c> ov) {
        
        Ordens_de_venda__c orders = (Ordens_de_venda__c) Trigger.new[0];
         
        // Lista de registros novos = Trigger.new
        Ordens_de_venda__c [] cancelOrders = [SELECT Id, Name, Status__c FROM Ordens_de_venda__c WHERE Status__c = 'Cancelado'];
        
        try{
            delete cancelOrders;
            //DeleteRecordsByStatus.redirectToHome();
            
            
        } catch (DmlException e){
            orders.addError('Registros não encontrados!!');

            
        }

    }   
     
}