force-app/main/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <description>Controle de estoque dos produtos cadastrados</description>
    <label>Estoque</label>
    <nameField>
        <label>Nome do produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoque de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estoque__c/fields/Mercadoria__c.field-meta.xml
<CustomField>
    <fullName>Mercadoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mercadoria</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercadorias__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercadorias__c</referenceTo>
    <relationshipLabel>Estoque de Produtos</relationshipLabel>
    <relationshipName>Estoque_de_Produtos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ordens_de_venda__c/ordens_de_venda__c.object-meta.xml
<CustomObject>
    <description>Local onde serão registrados todos os pedidos de venda</description>
    <label>Ordem de venda</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>ID do pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens de venda</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ordens_de_venda__c/fields/Mercadoria__c.field-meta.xml
<CustomField>
    <fullName>Mercadoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mercadoria</label>
    <referenceTo>Mercadorias__c</referenceTo>
    <relationshipLabel>Ordens de venda</relationshipLabel>
    <relationshipName>Ordens_de_venda</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AtualizaProdutoTriggerHandler.cls
public with sharing class AtualizaProdutoTriggerHandler {
    public static void run(System.TriggerOperation triggerEvent) {
   
        switch on triggerEvent{
            when AFTER_INSERT{
                afterInsert();
            }
 
            when AFTER_UPDATE{
             afterUpdate();
         }
            
        }
    }
 
    private static void afterInsert(){
        
        ordens_de_venda__c ordens = (ordens_de_venda__c) trigger.new[0];
        List <Estoque__c> estoque = EstoqueDAO.getStockProductById(ordens.Mercadoria__c);
        
        /*if(estoque.isEmpty()){
            update EstoqueDAO.updateRecord(produto);
        }
        */

    }

    private static void afterUpdate(){
        // Code here
    }

 
}