force-app/main/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <description>Controle de estoque dos produtos cadastrados</description>
    <label>Estoque</label>
    <nameField>
        <label>Nome do produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoque de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mercadorias__c/Mercadorias__c.object-meta.xml
<CustomObject>
    <label>Mercadoria</label>
    <nameField>
        <label>Nome de Mercadorias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercadorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mercadorias__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Marque a caixa se o produto está ativo ou não no sistema</inlineHelpText>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CadastrarProdutoNoEstoqueTriggerHandler.cls
public with sharing class CadastrarProdutoNoEstoqueTriggerHandler {

    public static void run(System.TriggerOperation triggerEvent) {
   
       switch on triggerEvent{
           when AFTER_INSERT{
               afterInsert();
           }

           when AFTER_UPDATE{
            afterUpdate();
        }
           
       }
   }

   private static void afterInsert(){
       Mercadorias__c produto = (Mercadorias__c) trigger.new[0];
       
       if(produto.Ativo__c == true){
           
           insert EstoqueDAO.createRecord(produto);
           List<Estoque__c> lista = EstoqueDAO.getStockProductById(produto.Id);

       }
   }

   private static void afterUpdate(){
    Mercadorias__c produto = (Mercadorias__c) trigger.new[0];

    if(produto.Ativo__c == true){
        
        List <Estoque__c> estoque = EstoqueDAO.getStockProductById(produto.id);
        /*for(Estoque__c e: estoque){
            system.debug(e.Name);
        }
        */
    
        if(estoque.isEmpty()){
			insert EstoqueDAO.createRecord(produto);
            //insert EstoqueDAO.createStockNumber(inserirEstoque);       
        }
        
    }

            
    }
        
}