force-app/main/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <description>Controle de estoque dos produtos cadastrados</description>
    <label>Estoque</label>
    <nameField>
        <label>Nome do produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoque de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estoque__c/fields/Estoque_atual__c.field-meta.xml
<CustomField>
    <fullName>Estoque_atual__c</fullName>
    <description>Estoque atualizado</description>
    <label>Estoque atual</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Estoque__c/fields/Mercadoria__c.field-meta.xml
<CustomField>
    <fullName>Mercadoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mercadoria</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercadorias__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercadorias__c</referenceTo>
    <relationshipLabel>Estoque de Produtos</relationshipLabel>
    <relationshipName>Estoque_de_Produtos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mercadorias__c/Mercadorias__c.object-meta.xml
<CustomObject>
    <label>Mercadoria</label>
    <nameField>
        <label>Nome de Mercadorias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercadorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mercadorias__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Marque a caixa se o produto está ativo ou não no sistema</inlineHelpText>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AtivacaoProdutoTriggerHandler.cls
public with sharing class AtivacaoProdutoTriggerHandler {
    public static void run (System.TriggerOperation triggerEvent) {
   
        switch on triggerEvent{

           /* when AFTER_INSERT{
                afterInsert();
            }
            */
 
            when AFTER_UPDATE{
                afterUpdate();
            }
            
        }
        
    }
    // Após o Estoque do produto estiver zerado, o mesmo é inativo, impedindo novas vendas no sistema.
    public static void afterUpdate (){
        Estoque__c estoque = (Estoque__c) trigger.New[0];

        List<Mercadorias__c> produtos = ProdutoDAO.getProductsById(estoque.Mercadoria__c);
        List<Mercadorias__c> produtosUpdate = new List<Mercadorias__c>();

        for(Mercadorias__c p: produtos){
            if(p.Id == estoque.Mercadoria__c ){
                if(estoque.Estoque_atual__c < = 0){
                    p.Ativo__c = false;
                }
            }
            produtosUpdate.add(p);
        }
        update produtosUpdate;
    }  


}