force-app/main/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <description>Controle de estoque dos produtos cadastrados</description>
    <label>Estoque</label>
    <nameField>
        <label>Nome do produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoque de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estoque__c/fields/Estoque_atual__c.field-meta.xml
<CustomField>
    <fullName>Estoque_atual__c</fullName>
    <description>Estoque atualizado</description>
    <label>Estoque atual</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Estoque__c/fields/Estoque_minimo__c.field-meta.xml
<CustomField>
    <fullName>Estoque_minimo__c</fullName>
    <description>Estoque mínimo de segurança exigido para o produto</description>
    <label>Estoque mínimo</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Estoque__c/fields/Mercadoria__c.field-meta.xml
<CustomField>
    <fullName>Mercadoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mercadoria</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercadorias__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercadorias__c</referenceTo>
    <relationshipLabel>Estoque de Produtos</relationshipLabel>
    <relationshipName>Estoque_de_Produtos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estoque__c/fields/Status_do_estoque__c.field-meta.xml
<CustomField>
    <fullName>Status_do_estoque__c</fullName>
    <label>Status do estoque</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Baixo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ordens_de_venda__c/ordens_de_venda__c.object-meta.xml
<CustomObject>
    <description>Local onde serão registrados todos os pedidos de venda</description>
    <label>Ordem de venda</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>ID do pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens de venda</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ordens_de_venda__c/fields/Mercadoria__c.field-meta.xml
<CustomField>
    <fullName>Mercadoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mercadoria</label>
    <referenceTo>Mercadorias__c</referenceTo>
    <relationshipLabel>Ordens de venda</relationshipLabel>
    <relationshipName>Ordens_de_venda</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ordens_de_venda__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Pendente</fullName>
                <default>true</default>
                <label>Em andamento</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AtualizaProdutoEstoqueTriggerHandler.cls
public with sharing class AtualizaProdutoEstoqueTriggerHandler {
    public static void run(System.TriggerOperation triggerEvent) {
   
        switch on triggerEvent{

            when AFTER_INSERT{
                afterInsert();
            }
 
            when AFTER_UPDATE{
                afterUpdate();
            }
            
        }
        
    }
 
    private static void afterInsert(){
      
        ordens_de_venda__c ordens = (ordens_de_venda__c) trigger.new[0];
        List <Estoque__c> estoque = EstoqueDAO.getStockProductById(ordens.Mercadoria__c);
        List<Estoque__C> estoqueInsert = new List<Estoque__c>();
        
        for(Estoque__c e: estoque){
            // Verifica se já existe o produto no objeto estoque
            if(e.Mercadoria__c == ordens.Mercadoria__c){
                // Verifica se a quantidade solicitada está disponível no estoque
                if(ordens.Quantidade__c <= e.Estoque_atual__c){
                    e.Estoque_atual__c -= ordens.Quantidade__c;
                    // Após subtração do valor no estoque, o campo Status é classificado de acordo com o valor disponível e o estoque mínimo    
                    if(e.Estoque_atual__c <= e.Estoque_minimo__c ){
                        e.Status_do_estoque__c = 'Baixo';
                    }else{
                    e.Status_do_estoque__c = 'Normal';
                    }
                    // Caso a quantidade atualizada seja maior que o disponível em estoque, ele retornará a mensagem na tela 
                }else{
                    ordens.addError('Quantidade máxima no estoque: '+e.Estoque_atual__c + ' Unidades.');  
                }   
            }
            estoqueInsert.add(e);
        }
        update estoqueInsert;
    }

    private static void afterUpdate(){

    // A ideia deste método é que, quando eu precisar atualizar a quantidade do pedido, ele faça a atualização da forma correta
    // Devolvendo a quantidade anterior para o estoque e subtraindo novamente com a quantidade nova.
        
         // Recuperando a quantidade do pedido antes da atualização
        ordens_de_venda__c ordensOld = (ordens_de_venda__c) trigger.old[0];

        // Instanciando o objeto para atualização com dados novos
        ordens_de_venda__c ordensNew = (ordens_de_venda__c) trigger.New[0];


        // Atualizando os dados
        List <Estoque__c> estoque = EstoqueDAO.getStockProductById(ordensNew.Mercadoria__c);
        List<Estoque__c> estoqueOld = EstoqueDAO.getStockProductById(ordensNew.Mercadoria__c);
        List<Estoque__c> estoqueAtualizado = new List <Estoque__c>();

        for(Estoque__c e: estoque){
            // Atualizar o pedido no estoque quando a quantidade for alterada
            if(e.Mercadoria__c == ordensNew.Mercadoria__c){
                // Voltando com o produto do pedido para o estoque
                e.Estoque_atual__c += ordensOld.Quantidade__c;
                if(ordensNew.Quantidade__c <= e.Estoque_atual__c){ 
                    // Subtraindo a nova quantidade
                    e.Estoque_atual__c -= ordensNew.Quantidade__c;
                     // Devolvendo o produto para o estoque quando o pedido for cancelado
                    if (ordensNew.Status__c == 'Cancelado'){
                        e.Estoque_atual__c += ordensNew.Quantidade__c;
                    } 
                    // Atualizar a pickList Status do estoque
                    if(e.Estoque_atual__c <= e.Estoque_minimo__c ){
                        e.Status_do_estoque__c = 'Baixo';
                    } else{
                        e.Status_do_estoque__c = 'Normal';
                    }
                }else{
                    ordensNew.addError('Quantidade máxima no estoque: '+e.Estoque_atual__c + ' Unidades.');
                }
            }

            estoqueAtualizado.add(e);        
        }
        update estoqueAtualizado;
    
    }
               
}