force-app/main/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <description>Controle de estoque dos produtos cadastrados</description>
    <label>Estoque</label>
    <nameField>
        <label>Nome do produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoque de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estoque__c/fields/Mercadoria__c.field-meta.xml
<CustomField>
    <fullName>Mercadoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mercadoria</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercadorias__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercadorias__c</referenceTo>
    <relationshipLabel>Estoque de Produtos</relationshipLabel>
    <relationshipName>Estoque_de_Produtos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mercadorias__c/Mercadorias__c.object-meta.xml
<CustomObject>
    <label>Mercadoria</label>
    <nameField>
        <label>Nome de Mercadorias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercadorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AtualizaInformacoesEstoqueTriggerHandler.cls
public with sharing class AtualizaInformacoesEstoqueTriggerHandler {
    public static void run(System.TriggerOperation triggerEvent) {

        switch on triggerEvent {

            when AFTER_UPDATE{
                afterUpdate();
            }
        }
    }

    // Caso precise atualizar o nome geral do produto no objeto produto, atualizar também o nome dele no estoque.
    // O relacionamento atualiza automaticamente, porém o nome geral não.
    private static void afterUpdate(){

        Mercadorias__c produtos = (Mercadorias__c) trigger.new[0];

        List <Estoque__c> estoque = EstoqueDAO.getStockProductById(produtos.Id);

        for(Estoque__c e: estoque){
            if(e.Mercadoria__c == produtos.Id){
                e.Name = produtos.Name;
            }
            update e;
        }
        

    }
}