force-app/main/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <description>Controle de estoque dos produtos cadastrados</description>
    <label>Estoque</label>
    <nameField>
        <label>Nome do produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoque de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estoque__c/fields/Estoque_atual__c.field-meta.xml
<CustomField>
    <fullName>Estoque_atual__c</fullName>
    <description>Estoque atualizado</description>
    <label>Estoque atual</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Estoque__c/fields/Mercadoria__c.field-meta.xml
<CustomField>
    <fullName>Mercadoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mercadoria</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercadorias__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercadorias__c</referenceTo>
    <relationshipLabel>Estoque de Produtos</relationshipLabel>
    <relationshipName>Estoque_de_Produtos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AlimentarEstoqueProdutoTriggerHandler.cls
public with sharing class AlimentarEstoqueProdutoTriggerHandler {
   
    public static void run(System.TriggerOperation triggerEvent) {
   
        switch on triggerEvent{
            when AFTER_INSERT{
                afterInsert();
            }
 
            /*when AFTER_UPDATE{
             afterUpdate();
         }*/
            
        }
    }

    private static void afterInsert(){
        // A trigger irá atuar no objeto Alimentação Estoque, onde após criação de um registro de quantidade de produto, irá atualizar no objeto estoque do produto 
        Alimentacao_Estoque__c inserirEstoque = (Alimentacao_Estoque__c) trigger.new[0];
        // Consulta para buscar informações do estoque do produto 
        List<Estoque__c> estoqueList = EstoqueDAO.getStockProductById(inserirEstoque.Mercadoria__c);
        // Lista que irá receber os registro a serem atualizados
        List<Estoque__c> estoqueUpdate = new List<Estoque__c>();

        system.debug('DEBUG ESTOQUE QUANTITY'+ estoqueList);
        
        for(Estoque__c e: estoqueList){
            if(e.Mercadoria__c == inserirEstoque.Mercadoria__c){
                e.Estoque_atual__c += inserirEstoque.Quantidade__c;
                system.debug('DEBUG DO ESTOQUE ATUALIZADO' + e.Estoque_atual__c);
            }
            system.debug('DEBUG CONTEÚDO DA LISTA' + e);
            estoqueUpdate.add(e);
            system.debug('DEBUG ESTOQUE UPDATE: '+ estoqueUpdate);
        }
        
        update estoqueUpdate;

    }

    
}