force-app/main/default/objects/Mercadorias__c/Mercadorias__c.object-meta.xml
<CustomObject>
    <label>Mercadoria</label>
    <nameField>
        <label>Nome de Mercadorias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercadorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mercadorias__c/fields/EAN__c.field-meta.xml
<CustomField>
    <fullName>EAN__c</fullName>
    <inlineHelpText>Teste de Integração</inlineHelpText>
    <label>EAN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/placeHolderWebServiceHandler.cls
public with sharing class placeHolderWebServiceHandler {
    public static void run(System.TriggerOperation triggerEvent) {
   
        switch on triggerEvent{
            when AFTER_INSERT{
                afterInsert();
            }
 
            when AFTER_UPDATE{
             afterUpdate();
         }
            
        }
    }

    private static void afterInsert(){
        // A trigger irá sempre rodar a classe de integração de produto assim que uma nova categoria for inserida/atualizada
        
        Mercadorias__c produtos = (Mercadorias__c) trigger.new[0];
        List<String> listEan = new List<String>();
        listEan.add(produtos.EAN__c);
        placeHolderWebService.calloutService(listEan);
    }
    private static void afterUpdate(){

        Mercadorias__c produtos = (Mercadorias__c) trigger.new[0];
        List<String> listEan = new List<String>();
        listEan.add(produtos.EAN__c);
        
        if(System.IsBatch() == false && System.isFuture() == false){ 
            placeHolderWebService.calloutService(listEan);
        }
    }
}