force-app/main/default/objects/Nota_Fiscal__c/Nota_Fiscal__c.object-meta.xml
<CustomObject>
    <label>Nota Fiscal</label>
    <nameField>
        <displayFormat>NF-{0000}</displayFormat>
        <label>Código da NF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas Fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_Fiscal__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nota_Fiscal__c/fields/Email_do_cliente__c.field-meta.xml
<CustomField>
    <fullName>Email_do_cliente__c</fullName>
    <label>Email do cliente</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Nota_Fiscal__c/fields/Mercadoria__c.field-meta.xml
<CustomField>
    <fullName>Mercadoria__c</fullName>
    <label>Mercadoria</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nota_Fiscal__c/fields/Ordem_de_venda__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_venda__c</fullName>
    <label>Ordem de venda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nota_Fiscal__c/fields/Valor_Total__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total__c</fullName>
    <label>Valor Total</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Nota_Fiscal__c/fields/Valor_Unitario__c.field-meta.xml
<CustomField>
    <fullName>Valor_Unitario__c</fullName>
    <label>Valor Unitario</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SendEmailTriggerHandler.cls
public with sharing class SendEmailTriggerHandler{
    public static void sendEmailNotification (List<Nota_Fiscal__c> listNf) {
        // Criação da Lista de email
        List<Messaging.Email>emailList = new List<Messaging.Email>();
        for(Nota_Fiscal__c nf : listNf){
            // Caso o campo e-mail do objeto Nota Fiscal estiver preenchido
            if(nf.Email_do_cliente__c != null){
                // Ele irá criar um email com as informações desejadas
                // Instanciando o objeito Messaging
                Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
                String[] toAdress = new String[]{nf.Email_do_cliente__c};
                emailMsg.setToAddresses(toAdress);
                String emailSubj = 'Pedido nº'+ nf.Ordem_de_venda__c;
                emailMsg.setSubject(emailSubj);
                String disName = 'Drogaria Silva&Nunes';
                emailMsg.setSenderDisplayName(disName);
                
                // Corpo da mensagem
                String content = 'Olá '+nf.Cliente__c + '<br>'+'Seu pedido nº ' + nf.Ordem_de_venda__c+ ' foi aprovado!!<br><br> '+
                +'<b>INFORMAÇOES:</b> <br>'+
                '<b>Produto:</b> '+nf.Mercadoria__c+'<br>'+
                '<b>Valor Unitário:</b> '+nf.Valor_Unitario__c+'<br>'+
                '<b>Quantidade:</b> '+nf.Quantidade__c+'<br>'+
                '<b>Valor total:</b> R$'+nf.Valor_Total__c;
                emailMsg.setHtmlBody(content);
                // Adicionando o email a lista de emails
                emailList.add(emailMsg);
                //

            }
        }
        // Enviando email
        Messaging.sendEmail(emailList);
    }
}