force-app/main/default/objects/Nota_Fiscal__c/Nota_Fiscal__c.object-meta.xml
<CustomObject>
    <label>Nota Fiscal</label>
    <nameField>
        <displayFormat>NF-{0000}</displayFormat>
        <label>Código da NF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas Fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_Fiscal__c/fields/Email_do_cliente__c.field-meta.xml
<CustomField>
    <fullName>Email_do_cliente__c</fullName>
    <label>Email do cliente</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Nota_Fiscal__c/fields/Valor_Total__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total__c</fullName>
    <label>Valor Total</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SendEmailTriggerHandlerTest.cls
@isTest
public with sharing class SendEmailTriggerHandlerTest {
    @isTest static void testSendEmailNotification() {
        List<Messaging.Email>emailList = new List<Messaging.Email>();
        
        Nota_Fiscal__c nfe = new Nota_Fiscal__c();
        nfe.Email_do_cliente__c = 'otavio3397@gmail.com'; 
        nfe.Quantidade__c = 2;
        nfe.Valor_Total__c = 200;
    
        Insert nfe;
        
        Test.startTest();
            if(nfe.Email_do_cliente__c != null){

                Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
                
                String[] toAdress = new String[]{'otavio3397@gmail.com'};
                emailMsg.setToAddresses(toAdress);
                emailMsg.setSubject('Pedido teste');
                emailMsg.setSenderDisplayName('Teste');
                // Corpo da mensagem
                emailMsg.setHtmlBody('Teste de email em html <br><br>');
                emailList.add(emailMsg);
                // Adicionando o email a lista de emails
            
                Messaging.sendEmail(emailList);
            }
        Test.stopTest();
        Integer invocations = Limits.getEmailInvocations();
        System.assertEquals(1, invocations, 'Um email deve ser enviado');
        }

    }