force-app/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Listagem de todas as categorias de produtos presentes na loja</description>
    <label>Categoria</label>
    <nameField>
        <label>Nome de Categoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <description>Controle de estoque dos produtos cadastrados</description>
    <label>Estoque</label>
    <nameField>
        <label>Nome do produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoque de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estoque__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Estoque de Produtos</relationshipLabel>
    <relationshipName>Estoque_de_Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estoque__c/fields/Estoque_atual__c.field-meta.xml
<CustomField>
    <fullName>Estoque_atual__c</fullName>
    <description>Estoque atualizado</description>
    <label>Estoque atual</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Estoque__c/fields/Estoque_minimo__c.field-meta.xml
<CustomField>
    <fullName>Estoque_minimo__c</fullName>
    <description>Estoque mínimo de segurança exigido para o produto</description>
    <label>Estoque mínimo</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Estoque__c/fields/Mercadoria__c.field-meta.xml
<CustomField>
    <fullName>Mercadoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mercadoria</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercadorias__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercadorias__c</referenceTo>
    <relationshipLabel>Estoque de Produtos</relationshipLabel>
    <relationshipName>Estoque_de_Produtos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estoque__c/fields/Status_do_estoque__c.field-meta.xml
<CustomField>
    <fullName>Status_do_estoque__c</fullName>
    <label>Status do estoque</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Baixo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mercadorias__c/Mercadorias__c.object-meta.xml
<CustomObject>
    <label>Mercadoria</label>
    <nameField>
        <label>Nome de Mercadorias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercadorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mercadorias__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Mercadorias</relationshipLabel>
    <relationshipName>Mercadorias</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mercadorias__c/fields/Estoque_minimo__c.field-meta.xml
<CustomField>
    <fullName>Estoque_minimo__c</fullName>
    <description>Estoque de segurança do produto</description>
    <inlineHelpText>Informe aqui o estoque mínimo definido para o produto</inlineHelpText>
    <label>Estoque mínimo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mercadorias__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <description>Quantidade de produtos que estão entrando no estoque</description>
    <inlineHelpText>Insira a quantidade de produtos a sem adicionados</inlineHelpText>
    <label>Quantidade</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ordens_de_venda__c/ordens_de_venda__c.object-meta.xml
<CustomObject>
    <description>Local onde serão registrados todos os pedidos de venda</description>
    <label>Ordem de venda</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>ID do pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens de venda</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ordens_de_venda__c/fields/Mercadoria__c.field-meta.xml
<CustomField>
    <fullName>Mercadoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mercadoria</label>
    <referenceTo>Mercadorias__c</referenceTo>
    <relationshipLabel>Ordens de venda</relationshipLabel>
    <relationshipName>Ordens_de_venda</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EstoqueDAO.cls
public  class EstoqueDAO {
    
    public static Estoque__c createRecord(Mercadorias__c produto) {

        Estoque__c st = new Estoque__c();
       
        st.Name = produto.Name;
        st.Mercadoria__c = produto.Id;
        st.Categoria__c = produto.Categoria__c;
        st.Estoque_atual__c = produto.Quantidade__c;
        st.Estoque_minimo__c = produto.Estoque_minimo__c;
        st.Status_do_estoque__c = 'Normal';
        
        return st;
    }

    
    /*public static Estoque__c updateRecord(ordens_de_venda__c ordens){
        
        Estoque__c st = new Estoque__c();

    }
    */
    

    public static List<Estoque__c> getStockProductById(Id id){
        
        return [SELECT Mercadoria__c, Name, Estoque_atual__c, Estoque_minimo__c FROM Estoque__c WHERE Mercadoria__c = :id];
       
    }


}